name: Build test images
on:
  push:
    branches:
      - "main"
  pull_request: {}

env:
  IMAGE_NAME_E2E: crc-e2e
  IMAGE_NAME_INTEGRATION: crc-integration

jobs:
  build-e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Work out correct id
        env:
          GH_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo $GH_CONTEXT > gh_context.json
          COMMIT_ID=$(cat gh_context.json | jq -r '.event.after')
          # if this is a new PR, .event.after is empty, use .sha instead in that case
          if [[ -z "$COMMIT_ID" ]]; then
            COMMIT_ID=$(cat gh_context.json | jq -r '.sha')
          fi
          echo "COMMIT_SHA=$COMMIT_ID" >> "$GITHUB_ENV"
          
      - name: Build and archive e2e image
        # use github.sha as ID to correlate various workflows triggered by the same event
        run: |
          CRC_E2E_IMG_VERSION=id-${{ env.COMMIT_SHA }} make containerized_e2e
          podman save -o ${{ env.IMAGE_NAME_E2E }}.tar quay.io/crcont/${{ env.IMAGE_NAME_E2E}}:id-${{ env.COMMIT_SHA }}

      - name: Upload e2e image
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.IMAGE_NAME_E2E }}-id${{ env.COMMIT_SHA }}
          path: ${{ env.IMAGE_NAME_E2E }}.tar

  build-integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Work out correct id
        env:
          GH_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo $GH_CONTEXT > gh_context.json
          COMMIT_ID=$(cat gh_context.json | jq -r '.event.after')
          # if this is a new PR, .event.after is empty, use .sha instead in that case
          if [[ -z "$COMMIT_ID" ]]; then
            COMMIT_ID=$(cat gh_context.json | jq -r '.sha')
          fi
          echo "COMMIT_SHA=$COMMIT_ID" >> "$GITHUB_ENV"

      - name: Build and archive integration image
        # use github.sha as ID to correlate various workflows triggered by the same event
        run: |
          CRC_INTEGRATION_IMG_VERSION=id-${{ env.COMMIT_SHA }} make containerized_integration
          podman save -o ${{ env.IMAGE_NAME_INTEGRATION }}.tar quay.io/crcont/${{ env.IMAGE_NAME_INTEGRATION }}:id-${{ env.COMMIT_SHA }}
      
      - name: Upload integration image
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.IMAGE_NAME_INTEGRATION }}-id${{ env.COMMIT_SHA }}
          path: ${{ env.IMAGE_NAME_INTEGRATION }}.tar